import type { BonsaiSpecimen } from "@/components/bonsai/bonsai-specimen-card"
import type { BonsaiPost } from "@/components/bonsai/post-card"

export const mockSpecimens: BonsaiSpecimen[] = [
  {
    id: "1",
    name: "Ancient Pine",
    species: "Japanese Black Pine",
    age: 45,
    health: "excellent",
    imageUrl: "/japanese-black-pine-bonsai.jpg",
    owner: "Zen Gardener",
    ownerId: "1",
  },
  {
    id: "2",
    name: "Maple Cascade",
    species: "Japanese Maple",
    age: 15,
    health: "good",
    imageUrl: "/japanese-maple-bonsai.jpg",
    owner: "Zen Gardener",
    ownerId: "1",
  },
  {
    id: "3",
    name: "Cherry Blossom",
    species: "Sakura Cherry",
    age: 30,
    health: "excellent",
    imageUrl: "/cherry-blossom-bonsai.jpg",
    owner: "Bonsai Master",
    ownerId: "2",
  },
  {
    id: "4",
    name: "Juniper Spirit",
    species: "Shimpaku Juniper",
    age: 60,
    health: "good",
    imageUrl: "/juniper-bonsai.jpg",
    owner: "Tree Whisperer",
    ownerId: "3",
  },
]

export const mockPosts: BonsaiPost[] = [
  {
    id: "1",
    specimenId: "1",
    specimenName: "Ancient Pine",
    imageUrl: "/japanese-black-pine-bonsai-spring.jpg",
    caption: "Spring growth is looking amazing this year! The needles are so vibrant.",
    owner: "Zen Gardener",
    ownerId: "1",
    ownerAvatar: "/zen-person.jpg",
    likes: 124,
    isLiked: false,
    timestamp: "2 hours ago",
    comments: 8,
  },
  {
    id: "2",
    specimenId: "3",
    specimenName: "Cherry Blossom",
    imageUrl: "/cherry-blossom-bonsai-flowers.jpg",
    caption: "First bloom of the season! 🌸",
    owner: "Bonsai Master",
    ownerId: "2",
    ownerAvatar: "/bonsai-master.jpg",
    likes: 256,
    isLiked: true,
    timestamp: "5 hours ago",
    comments: 15,
  },
  {
    id: "3",
    specimenId: "2",
    specimenName: "Maple Cascade",
    imageUrl: "/japanese-maple-bonsai-autumn.jpg",
    caption: "Autumn colors starting to show. Nature is such an artist.",
    owner: "Zen Gardener",
    ownerId: "1",
    ownerAvatar: "/zen-person.jpg",
    likes: 89,
    isLiked: false,
    timestamp: "1 day ago",
    comments: 5,
  },
  {
    id: "4",
    specimenId: "4",
    specimenName: "Juniper Spirit",
    imageUrl: "/juniper-bonsai-wiring.jpg",
    caption: "Just finished wiring this beautiful cascade. Took 3 hours but worth it!",
    owner: "Tree Whisperer",
    ownerId: "3",
    ownerAvatar: "/tree-expert.jpg",
    likes: 178,
    isLiked: false,
    timestamp: "2 days ago",
    comments: 12,
  },
]
